{
 "title": "Article and Comment Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Comment Cache hits per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "delta(comment_cache_hits_total[1m])",
     "legendFormat": "Comment Cache hits per minute"
    }
   ]
  },
  {
   "title": "Comment Cache misses per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "delta(comment_cache_misses_total[1m])",
     "legendFormat": "Comment Cache hits per minute"
    }
   ]
  },
  {
   "title": "Comment Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "comment_cache_hits_total", "legendFormat": "Hits" },
    { "expr": "comment_cache_misses_total", "legendFormat": "Misses" }
   ]
  },
  {
   "title": "Article Cache hits per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(article_cache_hits_total[1m])",
     "legendFormat": "Article Cache hits per minute"
    }
   ]
  },
  {
   "title": "Article Cache misses per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "delta(article_cache_misses_total[1m])",
     "legendFormat": "Article Cache misses per minute"
    }
   ]
  },
  {
   "title": "Article Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "expr": "article_cache_hits_total", "legendFormat": "Hits" },
    { "expr": "article_cache_misses_total", "legendFormat": "Misses" }
   ]
  },
  {
   "title": "Hit Ratios",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "article_cache_hit_ratio", "legendFormat": "Article Hit Ratio" },
    { "expr": "comment_cache_hit_ratio", "legendFormat": "Comment Hit Ratio" },
    {
     "expr": "avg_over_time(article_cache_hit_ratio[5m])",
     "legendFormat": "Article Hit Ratio Average"
    },
    {
     "expr": "avg_over_time(comment_cache_hit_ratio[5m])",
     "legendFormat": "Comment Hit Ratio Average"
    }
   ]
  }
 ]
}